// All data for the /more section.
// Update this file as your content evolves — blogs, poems, and quotes live here.

export const quotes = [
    { text: "When your winning you are not as good as you think you are, when your losing you are not as bad you think you are", author: "Unknown" },
    { text: "Money can buy you whatever you want, but not immortality, that you need to earn", author: "Matt Damon" },
    { text: "When the bare minimum is praised, mediocrity feels like success, and excellence starts to look unreal.", author: "Kamal Hassan" },
    { text: "A man without purpose searches for pleasure", author: "Unknown" },
    { text: "As long as the dice is rolling, you will get your six. For now, we clap for others and show love", author: "Unknown" },
    { text: "When expectation meets reality, Congratulations aren't due", author: "Verappan" },
    { text: "Nobody is born bad and nobody dies good", author: "Unknown" },
    { text: "God has a tendency of picking up a nobody and make them a somebody in front of everybody, without asking anybody", author: "Unknown" },
    { text: "It is crazy to know, that someone is not the same one with anyone but you", author: "Verappan" },
    { text: "Either I will find a way or I'll make one", author: "Verappan" },
    { text: "It is impossible for a person to learn something he already knows", author: "Unknown" },
    { text: "How good a kingdom is, when the king is not around, shows how good the king is", author: "Verappan" },
    { text: "Nothing is fair in love and war. We live in a world where wars happen all around everyday yet love keeps spreading", author: "Unknown" },
    { text: "You should never ask something to someone, who cant say no to you", author: "Verappan" },
    { text: "You don't know what real loss is until you have lost something that you love more than yourself", author: "Unknown" },
    { text: "The strongest of the men are those who care, but don't care to show that they do", author: "Verappan" },
    { text: "May God have mercy on my enemies, cause I won't", author: "Napolean" },
    { text: "If you don't resent what you deserve and didn't get. It means you never wanted it or deserved it", author: "Verappan" },
    { text: "The child who was not embraced by the village, will burn it down to feel its warmth", author: "African Proverb" },
    { text: "Code is poetry, but the real art is in the architecture.", author: "Unknown" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
    { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
];

export const poems = [
    {
        title: "Named Too Late",
        year: "2026",
        stanzas: [
            [
                "Sometimes I still wonder",
                "when exactly it changed,",
            ],
            [
                "which laugh of yours stayed too long in my head,",
                "which goodbye felt heavier than it should.",
            ],
            [
                "Maybe it was never sudden.",
                "Just small things piling up quietly.",
            ],
            [
                "Wanting to sit next to you every time.",
                "Checking if you reached home.",
                "Saving random memes",
                "just because \"you'd probably like this.\"",
            ],
            [
                "At first I called it \"being nice\".",
                "Then attachment.",
                "Then maybe just friendship exclusivity.",
            ],
            [
                "But love has a way of sitting silently",
                "until you accidentally name it.",
            ],
            [
                "And once I did,",
                "everything started hurting softly.",
            ],
            [
                "Not because you were cruel,",
                "you were kind in every possible way,",
                "except the way I secretly wished for.",
            ],
            [
                "I know I'm not the right match for her,",
                "but God, I so much wish I was.",
            ],
            [
                "People call it low self-esteem,",
                "I call it self-awareness.",
            ],
            [
                "So I never told you.",
            ],
            [
                "Because some confessions",
                "don't fail after being spoken,",
                "they fail long before they reach the mouth.",
            ],
            [
                "I learned to love you quietly instead,",
                "in borrowed moments,",
                "inside ordinary conversations,",
                "inside jokes you'd forget by tomorrow",
                "but I'd replay for weeks.",
            ],
            [
                "And maybe that's the saddest part,",
                "you never broke my heart.",
                "You just never held it.",
            ],
        ],
    },
    {
        title: "Nearby Desks",
        year: "2026",
        stanzas: [
            [
                "He pushed commits, and quietly feelings,",
                "She reviewed policies, untouched by such dealings.",
            ],
            [
                "He sent an invite, nervous and late,",
                "She thought team outing, not anything of fate.",
            ],
            [
                "Same office floors, different roles,",
                "A Systems heart, HR control.",
            ],
            [
                "WhatsApp jokes and lingering replies,",
                "Breakroom laughter that stayed in his mind.",
            ],
            [
                "She knew Tamil films,",
                "He smiled, surprised.",
                "Songs, scenes, shared grins,",
                "Moments quietly prized.",
            ],
            [
                "Office café, evening sun,",
                "He spoke with meaning, she heard none.",
            ],
            [
                "In her eyes, futures grew,",
                "Plans he made, she never knew.",
            ],
            [
                "He debugged courage, asked her clear,",
                "She smiled softly, \"Not what I'm looking for here.\"",
            ],
            [
                "The message was honest, simple, kind,",
                "Her answer gentle, but firm in mind.",
            ],
            [
                "Now nearby desks feel worlds apart,",
                "Same building still, but a quieter heart.",
            ],
            [
                "Some almosts stay almost",
            ],
        ],
    },
    {
        title: "Dilemma",
        year: "2026",
        stanzas: [
            [
                "My heart says yes, my mind says no",
                "Is this tug of love, where do I go",
                "I met a soul who feels like fate",
                "Too soon, too fast or just too late",
            ],
            [
                "He is kind, he is warm",
                "He has this charm",
                "He shares his dream, he holds my gaze",
                "And suddenly I'm losing in his dazed amaze",
            ],
            [
                "My butterflies they on strike",
                "flipping wings at feeling they don't like",
            ],
            [
                "I want a love in my life",
                "Is it too much to ask for",
                "I want a shoulder to cry, company for a new place to try",
                "Someone to care",
                "Laughs to share",
            ],
        ],
    },
    {
        title: "Corridors and Chaos",
        year: "2026",
        stanzas: [
            [
                "College love is crazy,",
                "and I'll tell you why it's the best,",
                "why it somehow feels louder,",
                "and softer than the rest.",
            ],
            [
                "A hundred places to go,",
                "a hundred ways to date,",
                "but loving the same girl in a hundred ways —",
                "that's the magic I can't translate.",
            ],
            [
                "Ethnic days meant pictures together,",
                "festivals came just as a reason for you,",
                "every event felt important somehow,",
                "only because I'd see you there too.",
            ],
            [
                "I thought if I made you smile,",
                "maybe you'd fall for me someday,",
                "but every time you did,",
                "I just lost myself a little more your way.",
            ],
            [
                "From that first \"hey… hi…\"",
                "to \"can you send me notes?\"",
                "from tea breaks and gossip",
                "to late-night texts we wrote,",
            ],
            [
                "Random calls that stretched for hours,",
                "minutes forgetting their place,",
                "bunking classes without regret,",
                "just to walk beside your pace.",
            ],
            [
                "Corridors turned into stories,",
                "benches into something more,",
                "every small, stupid moment",
                "felt like something worth living for.",
            ],
            [
                "And then came that question —",
                "\"Hey… can we go out?\"",
                "We didn't know why we went as a group,",
                "but somewhere there, I lost all doubt.",
            ],
            [
                "Because suddenly it hit me...",
                "quiet, deep, and true,",
                "I was already in love…",
                "long before I ever knew.",
            ],
            [
                "They say don't ask something",
                "to someone who can't say no,",
                "but I still asked you anyway,",
                "with a heart that couldn't let go.",
            ],
            [
                "\"Will you be my…\"",
                "and silence filled the air,",
                "glances spoke what words couldn't,",
                "and somehow, you were already there.",
            ],
            [
                "What we had, turned sacred,",
                "something soft, yet forever strong,",
                "from \"I hope this lasts\"",
                "to \"I know where I belong.\"",
            ],
            [
                "We started making each other better,",
                "in ways no one else could see,",
                "you showed me parts of myself",
                "I didn't know could be me.",
            ],
            [
                "A version I'd never shown the world,",
                "a side I never knew I had,",
                "and somehow, without trying,",
                "you made even my worst days less bad.",
            ],
            [
                "College love is crazy,",
                "but maybe that's why it's true,",
                "it's in the smallest things,",
                "in everything that leads me to you.",
            ],
            [
                "And if I had a hundred lives,",
                "with a hundred different views,",
                "I'd still fall in love like this,",
                "in corridors…",
                "in chaos…",
                "in college…",
                "with you.",
            ],
        ],
    },
    {
        title: "Pressure Is a Privilege",
        year: "2026",
        stanzas: [
            [
                "The hardest choices are made by the strongest men",
                "The strongest men are made by the hardest times",
                "Pressure is a privilege",
                "Plan like you are gonna live for 100 years",
                "Live like you are gonna die tomorrow",
            ],
        ],
    },
];

export const blogs = [
    {
        slug: "spacex-ipo",
        title: "The SpaceX IPO — A Log of what I know",
        excerpt: "A $1.75 trillion company with a $4.9 billion loss wants your money. Here's everything you need to know before you make that call.",
        date: "2026-06-13",
        readingTime: "8 min read",
        link: "https://medium.com/@smverappan/the-spacex-ipo-a-log-of-what-i-know-30b3fbb895d5",
        content: [
            { type: "heading" as const, text: "The Numbers, First" },
            { type: "paragraph" as const, text: "On June 12, 2026, SpaceX lists on Nasdaq under the ticker SPCX. The price is $135 per share, a fixed number with no auction, no price range, no negotiation still 4x oversubscribed. This alone is unusual. Goldman Sachs, leading a 21-bank syndicate, is selling 555.5 million shares to raise $75 billion. With the underwriter greenshoe option (an option to sell an additional 83.3 million shares if demand exceeds supply) exercised, that becomes $86.7 billion. At $135 a share, SpaceX is valued at **$1.75 trillion**, making it the seventh-largest company in the United States on day one, right above Tesla's current market cap of around $1.6 trillion." },
            { type: "paragraph" as const, text: "Elon Musk will own 42% of the equity and retain more than 82% of the voting control. He is locked up for 366 days before he can sell a single share. His stake on paper: roughly $866 billion." },
            { type: "paragraph" as const, text: "But here is the part that makes you pause. SpaceX is only selling about 4.2% of the company. The other 95.8% is not going anywhere on listing day. As NC State put it, SpaceX is \"**selling roughly 4.2% of the company to establish a price for the other 95.8%**\". That is standard IPO structure, but at this scale it means a $1.75 trillion enterprise is being priced on an exceptionally thin float. Thin floats move fast, in both directions." },
            { type: "heading" as const, text: "The Index Funds Are Already Coming" },
            { type: "paragraph" as const, text: "Here is something that rarely gets mentioned in the same breath as the IPO itself. Within 15 trading days of listing, SpaceX is expected to be included in the Nasdaq 100 and FTSE Russell indexes. Nasdaq literally changed its rules in 2026 to allow **\"fast entry\"** for mega-cap IPOs and SpaceX was the obvious catalyst for that change." },
            { type: "paragraph" as const, text: "What that means in practice: every index fund and ETF that tracks those benchmarks will be forced to buy SpaceX shares automatically, whether or not a fund manager personally believes in the valuation. BNP Paribas estimates that Nasdaq 100 inclusion alone will generate around $8 billion in passive buying in the first month. Roughly 30% of SpaceX's entire free float could be absorbed by passive funds within 15 trading days, according to index forecasting firms." },
            { type: "paragraph" as const, text: "This creates a mechanical buying wave immediately after listing, which inflates the stock price, which increases SpaceX's weight in the index, which forces funds to buy even more to stay properly allocated. That cycle runs upward until insiders start selling." },
            { type: "paragraph" as const, text: "**Simpler:**" },
            { type: "paragraph" as const, text: "When SpaceX gets added to an index, many big funds are **forced to buy the stock automatically**, which pushes the price up. As the price rises, the stock becomes a bigger part of the index, so funds buy even more, until early investors/company insiders start selling and slow the rise." },
            { type: "heading" as const, text: "What SpaceX Actually Makes" },
            { type: "paragraph" as const, text: "SpaceX filed its first-ever public financials in May 2026. The numbers are real, and they are worth reading carefully." },
            { type: "paragraph" as const, text: "**Full year 2025:**" },
            { type: "listItem" as const, text: "Total revenue: $18.67 billion (up 33% year-over-year)" },
            { type: "listItem" as const, text: "Net loss: $4.9 billion" },
            { type: "listItem" as const, text: "Adjusted EBITDA: $6.6 billion" },
            { type: "listItem" as const, text: "Capital expenditure: $20.7 billion" },
            { type: "paragraph" as const, text: "The business has three segments. **Starlink**, the satellite internet service, generated $11.4 billion in revenue in 2025 (61% of the company) and produced $4.4 billion in operating profit (money the segment made after its own costs, before company-wide expenses). It is the only segment that makes money. Subscribers grew from 4.6 million at end-2024 to 8.9 million at end-2025, and to 10.3 million by Q1 2026. That is a real, growing, subscription business." },
            { type: "paragraph" as const, text: "The **Space segment**, meaning rocket launches, payload delivery, NASA crew missions, generated $4.1 billion in revenue but operated at a $657 million operating loss (costs exceeded what it brought in). SpaceX spent close to $3 billion in that segment on Starship R&D alone." },
            { type: "paragraph" as const, text: "The **AI segment**, which houses xAI, the Grok chatbot, and X (formerly Twitter), generated $3.2 billion in revenue but posted a $6.4 billion operating loss." },
            { type: "paragraph" as const, text: "Before SpaceX absorbed xAI in February 2026, the company was actually profitable. It had reported a $791 million net profit in 2025. The xAI merger flipped that entirely." },
            { type: "paragraph" as const, text: "The valuation of $1.75 trillion against $18.67 billion in annual revenue is a price-to-sales ratio of roughly 94x. Think of it this way: you are paying $94 for every $1 the company currently earns. Goldman Sachs is pitching this with a single number: that SpaceX's AI division revenue will grow from $3.2 billion today to $322 billion by 2030, a 100x increase in five years." },
            { type: "heading" as const, text: "The Comparison That Should Give You Pause" },
            { type: "paragraph" as const, text: "When Google went public in August 2004, it priced at $85 per share for a valuation of $23 billion. Its trailing twelve-month revenue was $3.2 billion and it was profitable. Its price-to-sales multiple at IPO was around 7x. Investors called that expensive. Those investors were wrong, because Google was already dominant in search and compounding at 100% revenue growth per year." },
            { type: "paragraph" as const, text: "Amazon IPO'd in May 1997 at $18 per share for a market cap of roughly $438 million. Revenue was around $16 million. It had no profits. Its entire bull case rested on the idea that physical retail could be replaced by e-commerce, an idea that was genuinely radical in 1997, and one that took fifteen years to fully arrive." },
            { type: "paragraph" as const, text: "SpaceX comes to market at a **94x** price-to-sales on revenue that includes a deeply loss-making AI unit it acquired four months ago. The bull case requires believing that an AI division losing $2.5 billion per quarter will generate more revenue in 2030 than Nvidia's entire fiscal 2024 revenue of $61 billion." },
            { type: "paragraph" as const, text: "Goldman Sachs, it is worth noting, is also the lead underwriter on this deal, which means it gets paid when the IPO succeeds. The projection and the incentive structure are not independent." },
            { type: "heading" as const, text: "Why Are People Still Buying This" },
            { type: "paragraph" as const, text: "Starlink has 10 million paying subscribers, zero real orbital competitors, and posted $4.4 billion in operating profit last year. Falcon 9 controls over 60% of the global commercial launch market and is the most reliable orbital rocket ever built. Starship, if it reaches design goals, makes every competitor's cost structure obsolete overnight. These are not projections. These are facts on the ground today. The people writing the largest checks into this IPO are not naive, they are betting that Starlink alone, priced as a standalone subscription business, is worth more than $1 trillion, and the rockets and AI are essentially free upside. That is a reasonable argument." },
            { type: "heading" as const, text: "The Musk Shell Game — And Why It Should Affect Your View of the IPO" },
            { type: "paragraph" as const, text: "To understand why xAI ended up inside SpaceX four months before this IPO, you have to follow the sequence of events. And this is where the story gets a little Wolf of Wall Street." },
            { type: "paragraph" as const, text: "Musk bought Twitter for $44 billion in October 2022. The platform shed advertisers rapidly. Revenue dropped. The brand became politically polarizing, which accelerated that advertiser retreat. By early 2025, X was a money-losing platform carrying roughly $12 billion in debt." },
            { type: "paragraph" as const, text: "Here is the part worth paying attention to. When xAI acquired X in March 2025 in an all-stock deal, it valued Twitter at $33 billion, roughly $11 billion less than Musk originally paid for it. That lower valuation was not an admission of failure. In a deal between two Musk-controlled private companies, both represented by the same bank (Morgan Stanley), the valuation is whatever Musk decides it is, as long as investors do not revolt. Critics noted at the time that xAI's own valuation jumped from roughly $50 billion to $80 billion in the transaction, with no new money involved. The math was flexible in a way that only works when one person controls both sides of the negotiation. (Musk said my chocolates are worth 10$ and sold it to Musk)" },
            { type: "paragraph" as const, text: "Then in February 2026, SpaceX acquired xAI entirely in an all-stock deal, creating the combined $1.25 trillion entity that is now going public. This brought X (Twitter), Grok, and all of xAI's losses onto SpaceX's balance sheet." },
            { type: "paragraph" as const, text: "So, what you are investing in is not a rocket and satellite company, it is a **rocket-plus-AI-plus-social-media company**." },
            { type: "paragraph" as const, text: "Meanwhile in another story, Tesla, the public company whose shareholders had no meaningful say in any of this, invested $2 billion in xAI in January 2026 as part of a $20 billion funding round. So, Tesla shareholders watching Tesla go down in stock price, revenue and vehicle sales saw Musk write a **$2 billion check into his AI startup**." },
            { type: "paragraph" as const, text: "The pattern across these transactions is consistent. Musk moved a cash-burning, debt-laden social media platform from his personal balance sheet through xAI, then into SpaceX, where it became part of a company going public. Each step was legal. Each step also passed losses from entities where accountability was limited (private companies, Musk personally) to entities where accountability is distributed (public shareholders and now retail investors). The accumulated deficit on SpaceX's books currently stands at $41.3 billion." },
            { type: "paragraph" as const, text: "**Now the important lockup question.** In a typical IPO, all early investors are locked out of selling for 180 days. SpaceX is doing something structurally different. Existing investors (venture funds, early backers who have held for years, including xAI and X investors who just had their stakes converted into SpaceX shares) can begin selling 20% of their holdings as early as two days after SpaceX reports its first quarterly earnings as a public company, likely in August. Further tranches unlock at 70, 90, 105, 120, and 135 days post-IPO, at 7% each time. Musk himself is locked for a full 366 days." },
            { type: "paragraph" as const, text: "So the timeline looks like this: index funds mechanically buy the stock in the first 15 days, pushing the price up. That creates a window where Musk's early backers, some of whom have been holding since SpaceX was worth a fraction of today's valuation and Twitter investors who watched their stake lose value for three years, are now all sitting on SpaceX shares. The IPO, and the index fund buying wave it triggers, gives them a clean, liquid, high-priced exit." },
            { type: "heading" as const, text: "The Bottom Line" },
            { type: "paragraph" as const, text: "SpaceX is one of the most genuinely impressive companies ever built. Starlink is profitable, growing and has no real orbital competitor. Falcon 9 controls 60% of the global launch market. Starship, if it works at scale, changes the economics of space access entirely (reusable rockets, space-based infrastructure, interplanetary access and many more..)." },
            { type: "paragraph" as const, text: "But the SpaceX IPO is not just a rocket company going public. It is a company that absorbed a cash-burning AI startup, which itself had absorbed a cash-burning social media platform, four months before its listing date. The losses of those acquisitions are now on the balance sheet of a company asking public investors to pay 94 times annual sales based on projections that require 100x growth in five years from an AI division that currently operates at a $2.5 billion quarterly loss." },
            { type: "paragraph" as const, text: "The index funds will buy automatically. The insiders can start selling in August. The retail investors holding at $135 are in between those two forces." },
            { type: "paragraph" as const, text: "If you buy SPCX at $135, you are not buying Starlink. You are buying Goldman Sachs's forecast for a $322 billion AI business that does not yet exist, at a price that assumes it will." },
            { type: "paragraph" as const, text: "That is either the greatest bet of the decade, or the most expensive lesson the retail market has ever been invited to learn." },
            { type: "paragraph" as const, text: "The choice is yours. It always is." },
        ],
    },
    {
        slug: "startup-mistakes",
        title: "The Startup Mistakes That Don't Look Like Mistakes",
        excerpt: "Most startup mistakes don't feel like mistakes when we're making them. They feel like progress. Like ambition.",
        date: "2026-06-12",
        readingTime: "6 min read",
        link: "https://medium.com/@smverappan/the-startup-mistakes-that-dont-look-like-mistakes-0b60978575ce",
        content: [
            { type: "paragraph" as const, text: "There's a certain romanticism around startups. The late nights, the hustle, the \"we're building something big\" energy. But behind that, most early-stage founders are quietly making the same mistakes. Most startup mistakes don't feel like mistakes when we're making them. **They feel like progress. Like ambition.**" },
            { type: "paragraph" as const, text: "My friends and I have made a lot of them. I've seen others make the same ones. And what's interesting is, these mistakes aren't random. They follow patterns." },
            { type: "paragraph" as const, text: "Here are the ones that show up again and again. If you're building a SaaS product or a client-driven company, these might save you time, money and a lot of frustration." },
            { type: "paragraph" as const, text: "Let's do a **13 Reasons Why**" },
            { type: "heading" as const, text: "1. Building Too Much, Too Early" },
            { type: "paragraph" as const, text: "In the early days, building feels productive. So we build more. More features. More flows. More \"just in case\" functionality." },
            { type: "paragraph" as const, text: "We think more features = more value. But in reality, more features = more confusion." },
            { type: "paragraph" as const, text: "Users don't want 20 features. They want one thing that works insanely well." },
            { type: "paragraph" as const, text: "Ship small. Ship focused. Let users pull features out of you instead of pushing everything at once." },
            { type: "paragraph" as const, text: "Early Instagram (back when it was Burbn) had check-ins, plans, photos and everything. No one cared. They stripped it down to just photo sharing. **That's when it clicked.**" },
            { type: "paragraph" as const, text: "Even Lego almost collapsed because they expanded into too many product lines. They survived by going back to their core." },
            { type: "paragraph" as const, text: "**Focus wins. Depth beats breadth**. But also, sometimes early overbuilding helps exploration, but only if you're consciously experimenting, not blindly expanding." },
            { type: "heading" as const, text: "2. Building Without Commitment" },
            { type: "paragraph" as const, text: "This one hurts the most." },
            { type: "paragraph" as const, text: "We build for a \"potential client.\" They seem interested. They say things like _\"this looks great\"_." },
            { type: "paragraph" as const, text: "So you spend weeks building. Then they disappear." },
            { type: "paragraph" as const, text: "The uncomfortable truth: **Interest is not commitment.**" },
            { type: "paragraph" as const, text: "Smart founders flip this:" },
            { type: "listItem" as const, text: "Get an MOU, or at least written confirmation" },
            { type: "listItem" as const, text: "Validate willingness to pay" },
            { type: "listItem" as const, text: "If needed, build a **tiny** prototype (2–3 days max, one person)" },
            { type: "paragraph" as const, text: "Dropbox didn't even build the product first, they validated demand with a simple demo video." },
            { type: "paragraph" as const, text: "I have spent weeks, went to in-person meets with a client who just decided to conveniently ghost us cause, we thought no need for an MOU, we got them through a known contact and we are new ourselves." },
            { type: "paragraph" as const, text: "**Why we do this**: Fear of asking for commitment. Fear of rejection." },
            { type: "heading" as const, text: "3. Falling in Love With the Solution, Not the Problem" },
            { type: "paragraph" as const, text: "With today's AI coding tools, building is easier than thinking and that's the problem. AI Tools push us into feature creep" },
            { type: "paragraph" as const, text: "We start with: \"What can I build?\"" },
            { type: "paragraph" as const, text: "Instead of: \"What problem is painful enough to solve?\"" },
            { type: "paragraph" as const, text: "As Paul Graham puts it, \"Make something people want.\"" },
            { type: "paragraph" as const, text: "Work backwards from the problem, not forward from the tech. Simple. But most founders reverse it. **Pattern:** Strong startups are obsessed with the problem. Weak ones are obsessed with the product." },
            { type: "heading" as const, text: "4. Not Having a Real Moat" },
            { type: "paragraph" as const, text: "If your product can be easily copied, it will be." },
            { type: "paragraph" as const, text: "The advantage doesn't have to be technical. It can be:" },
            { type: "listItem" as const, text: "Distribution (partnerships, networks)" },
            { type: "listItem" as const, text: "Technology (something hard to replicate)" },
            { type: "listItem" as const, text: "Supply chain or data advantage" },
            { type: "listItem" as const, text: "Market timing (entering early or underserved niches)" },
            { type: "paragraph" as const, text: "Peter Thiel talks about this in **Zero to One**, great companies don't win by competing better, they win by being different. Distribution and positioning often matter more than product." },
            { type: "paragraph" as const, text: "Two teams build the same AI tool(let's say notes summarizer)." },
            { type: "paragraph" as const, text: "One ships a better product." },
            { type: "paragraph" as const, text: "The other signs partnerships and integrates deeply into workflows." },
            { type: "paragraph" as const, text: "A year later, the second one wins, not because it built better, but because it built _where it's hard to leave_." },
            { type: "heading" as const, text: "5. Trying to Serve Everyone (Instead of Owning a Niche)" },
            { type: "paragraph" as const, text: "If you're building for everyone, you're building for no one." },
            { type: "paragraph" as const, text: "Start narrow:" },
            { type: "listItem" as const, text: "One niche" },
            { type: "listItem" as const, text: "One problem" },
            { type: "listItem" as const, text: "One type of customer" },
            { type: "paragraph" as const, text: "Dominate that space, then expand." },
            { type: "paragraph" as const, text: "Facebook started only for Harvard students. That constraint made it strong. You can't scale what you haven't nailed." },
            { type: "heading" as const, text: "6. Not Knowing Your Customer (ICP)" },
            { type: "paragraph" as const, text: "We don't need a perfect ICP on day one. But you must actively discover it:" },
            { type: "listItem" as const, text: "Talk to users" },
            { type: "listItem" as const, text: "Observe behavior" },
            { type: "listItem" as const, text: "Refine constantly" },
            { type: "paragraph" as const, text: "Slack worked because it deeply understood team workflows — not \"everyone who chats.\"" },
            { type: "paragraph" as const, text: "**Clarity on who leads to clarity on what.**" },
            { type: "heading" as const, text: "7. Weak Positioning" },
            { type: "paragraph" as const, text: "If your product takes too long to explain, it's already losing." },
            { type: "paragraph" as const, text: "Strong positioning: \"Use this → get this result\"" },
            { type: "paragraph" as const, text: "Weak positioning: \"First integrate this, then configure that…\"" },
            { type: "paragraph" as const, text: "Clarity isn't marketing, it's strategy. Winning startups are easy to explain in one line. Clarity converts. Complexity kills." },
            { type: "paragraph" as const, text: "Two companies build similar products." },
            { type: "paragraph" as const, text: "One explains features." },
            { type: "paragraph" as const, text: "The other explains outcomes." },
            { type: "paragraph" as const, text: "The second one wins." },
            { type: "paragraph" as const, text: "Stripe didn't say \"integrate complex payment systems.\"" },
            { type: "paragraph" as const, text: "It said, \"accept payments in minutes.\"" },
            { type: "paragraph" as const, text: "That difference is positioning." },
            { type: "heading" as const, text: "8. Ignoring the Economics (Until It Breaks)" },
            { type: "paragraph" as const, text: "A feature isn't just \"cool\", it has a cost. A common blind spot." },
            { type: "paragraph" as const, text: "Imagine building a food image analysis feature:" },
            { type: "listItem" as const, text: "High AI API cost per request" },
            { type: "listItem" as const, text: "Users unwilling to pay enough to cover it" },
            { type: "paragraph" as const, text: "Now every user loses you money. Before building, ask:" },
            { type: "paragraph" as const, text: "What does this cost per user?" },
            { type: "paragraph" as const, text: "What will users realistically pay?" },
            { type: "paragraph" as const, text: "If the math doesn't work, don't build it." },
            { type: "paragraph" as const, text: "Even large companies like Zomato have struggled with unit economics." },
            { type: "paragraph" as const, text: "At minimum, track KPIs, you don't need an MBA for it:" },
            { type: "listItem" as const, text: "Burn rate" },
            { type: "listItem" as const, text: "Runway" },
            { type: "listItem" as const, text: "Churn" },
            { type: "listItem" as const, text: "Cost per user" },
            { type: "paragraph" as const, text: "\"We'll figure it out later.\" won't work here. Bad economics don't fix themselves at scale. And don't spend it because you have money. Every expense should answer: \"Does this directly help us survive or grow?\"" },
            { type: "subheading" as const, text: "Don't Ignore Fixed vs Variable Costs (Especially in SaaS)" },
            { type: "paragraph" as const, text: "In SaaS:" },
            { type: "listItem" as const, text: "Fixed costs: Servers (baseline), salaries, tools" },
            { type: "listItem" as const, text: "Variable costs: API calls, usage-based infra, per-user costs" },
            { type: "paragraph" as const, text: "If your variable cost scales faster than revenue, growth will hurt you." },
            { type: "paragraph" as const, text: "Good SaaS businesses have: **High margins + predictable costs**" },
            { type: "paragraph" as const, text: "Zomato grew fast on discounts, but every order lost money. Every order came with high delivery and operational costs." },
            { type: "paragraph" as const, text: "More growth = more loss." },
            { type: "paragraph" as const, text: "They fixed it by cutting discounts, improving margins, and adding new revenue streams. **That's the difference between growth and sustainable growth.**" },
            { type: "heading" as const, text: "9. Building around ONE user." },
            { type: "paragraph" as const, text: "Working closely with a strong voice, a key opinion leader or early client, feels productive. But over time, your product becomes _their_ product." },
            { type: "paragraph" as const, text: "Instead:" },
            { type: "listItem" as const, text: "Talk to multiple users" },
            { type: "listItem" as const, text: "Look for patterns, not opinions" },
            { type: "paragraph" as const, text: "If you build shoes only for Cinderella, only she gets to the ball. Everyone else is left standing outside." },
            { type: "heading" as const, text: "10. Founder Misalignment (Especially With Friends)" },
            { type: "paragraph" as const, text: "Starting with friends feels natural. Until expectations diverge." },
            { type: "paragraph" as const, text: "Set structure early:" },
            { type: "listItem" as const, text: "Clear roles and responsibilities" },
            { type: "listItem" as const, text: "Short, focused meetings ( A rule I learnt from my friend — No meeting should cross 30 mins)" },
            { type: "listItem" as const, text: "Document decisions" },
            { type: "paragraph" as const, text: "Even great companies like Apple had internal conflicts early on. People assume alignment instead of defining it. Friendship doesn't replace structure." },
            { type: "heading" as const, text: "11. Scaling Too Early" },
            { type: "paragraph" as const, text: "Hiring, expanding, spending ➡ it feels like growth. But premature scaling kills startups." },
            { type: "paragraph" as const, text: "This is one of the most common patterns seen in Y Combinator companies and it stems from the pressure to look like a \"real company.\" **Small, focused teams win early**." },
            { type: "paragraph" as const, text: "Take Quibi." },
            { type: "paragraph" as const, text: "They raised huge money, hired aggressively, spent heavily on content, before proving real user demand." },
            { type: "paragraph" as const, text: "The result? Massive scale… with no foundation. It shut down within months." },
            { type: "paragraph" as const, text: "Now contrast that with Telegram." },
            { type: "paragraph" as const, text: "Telegram serves hundreds of millions of users with a surprisingly small team(30 to 40)." },
            { type: "heading" as const, text: "12. Ignoring Distribution" },
            { type: "paragraph" as const, text: "A great product doesn't guarantee users." },
            { type: "paragraph" as const, text: "Distribution does." },
            { type: "paragraph" as const, text: "Many founders assume:" },
            { type: "paragraph" as const, text: "\"If it's good, people will come.\"" },
            { type: "paragraph" as const, text: "They won't." },
            { type: "paragraph" as const, text: "Your edge might not be the product, it might be: Partnerships, Communities, Existing networks" },
            { type: "paragraph" as const, text: "Dropbox didn't just rely on the product, they used referrals (\"get extra storage\") to drive growth." },
            { type: "paragraph" as const, text: "Airbnb hacked early distribution by tapping into Craigslist users." },
            { type: "paragraph" as const, text: "Products don't spread. Distribution does." },
            { type: "heading" as const, text: "13. Legal and Structural Blind Spots" },
            { type: "paragraph" as const, text: "Legal issues don't show up early. But when they do, they're expensive." },
            { type: "paragraph" as const, text: "Things founders delay:" },
            { type: "listItem" as const, text: "Company registration" },
            { type: "listItem" as const, text: "Contracts & MOUs" },
            { type: "listItem" as const, text: "IP / patents" },
            { type: "listItem" as const, text: "Compliance (like HIPAA, GDPR)" },
            { type: "paragraph" as const, text: "Usually it goes like, \"We'll figure it out later.\"" },
            { type: "paragraph" as const, text: "That \"later\" becomes blocked deals, lost IP, or compliance risks." },
            { type: "paragraph" as const, text: "Theranos built a revolutionary health-tech product and partnered with major players like Walgreens." },
            { type: "paragraph" as const, text: "But behind the scenes:" },
            { type: "listItem" as const, text: "Lack of proper validation and regulatory compliance" },
            { type: "listItem" as const, text: "Misrepresentation of capabilities" },
            { type: "paragraph" as const, text: "Eventually, everything collapsed, partly because the company couldn't meet regulatory and legal standards." },
            { type: "heading" as const, text: "Final Words" },
            { type: "paragraph" as const, text: "Most startup advice sounds obvious. And yet, almost every founder makes some version of these mistakes." },
            { type: "paragraph" as const, text: "The goal isn't to avoid every mistake. It's to **recognize them early and not repeat them too long.**" },
        ],
    },
];
