// All data for the /more section.
// Update this file as your content evolves — blogs, poems, and quotes live here.

export const quotes = [
    { text: "Code is poetry, but the real art is in the architecture.", author: "Unknown" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
    { text: "Programs must be written for people to read, and only incidentally for machines to execute.", author: "Harold Abelson" },
    { text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", author: "Martin Fowler" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
    { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
    { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
    { text: "Whether you think you can, or you think you can't — you're right.", author: "Henry Ford" },
    { text: "The mind is not a vessel to be filled, but a fire to be ignited.", author: "Plutarch" },
];

export const poems = [
    {
        title: "The Algorithm of Time",
        year: "2023",
        stanzas: [
            [
                "In lines of code I seek the dawn,",
                "Each function built before the light.",
                "I push and pull from dusk to drawn,",
                "The logic of a sleepless night.",
            ],
            [
                "The bugs persist, the cursor blinks,",
                "A terminal, my canvas bare.",
                "Between the brackets something thinks —",
                "A mind that learns to care.",
            ],
        ],
    },
    {
        title: "Between Meetings",
        year: "2024",
        stanzas: [
            [
                "The whiteboard holds the world's design,",
                "A strategy in coloured ink.",
                "They ask me where we draw the line —",
                "I pause. I breathe. I think.",
            ],
            [
                "The data tells a story here",
                "Of patterns no one stopped to see.",
                "I chart the path through doubt and fear,",
                "And call it clarity.",
            ],
        ],
    },
    {
        title: "Midnight Deploy",
        year: "2025",
        stanzas: [
            [
                "3 AM, the server hums,",
                "A diff that could have waited.",
                "The pipeline runs, the silence comes —",
                "Green lights. Validated.",
            ],
            [
                "They'll wake to find the world improved",
                "By half a second's gain.",
                "And no one sees the hand that moved,",
                "Only what was changed.",
            ],
        ],
    },
    {
        title: "The Weight of Building",
        year: "2024",
        stanzas: [
            [
                "There is a weight to building things,",
                "An ache beneath the cursor's blink.",
                "Each function carries what it brings:",
                "A world too vast to stop and think.",
            ],
            [
                "The nights collapse to morning light,",
                "The stack trace scrolls, the diff grows wide.",
                "I chase the bug through endless sight,",
                "Not knowing what I've lost inside.",
            ],
            [
                "Some days the logic won't resolve,",
                "The error message cold and plain.",
                "I stare at what I cannot solve",
                "And run the whole search once again.",
            ],
            [
                "Then comes a moment — clean, exact —",
                "When every test turns finally green.",
                "No warning fires, no uncaught fact:",
                "The system runs like it should mean.",
            ],
            [
                "I push to main at half past three,",
                "The pipeline passes, all reviewed.",
                "For someone I will never see:",
                "A small thing done. A problem soothed.",
            ],
            [
                "And that is why the work goes on,",
                "Why I return to empty files.",
                "Not glory when the night is gone —",
                "Just this: to build what serves a while.",
            ],
        ],
    },
];

export const blogs = [
    {
        slug: "neural-networks",
        title: "Understanding Neural Networks",
        excerpt: "A deep dive into the architecture and math behind neural networks.",
        date: "2024-01-15",
        readingTime: "6 min read",
        content: [
            { type: "paragraph" as const, text: "Neural networks have become the backbone of modern AI. From image recognition to natural language processing, they power the systems we interact with every day. But what exactly are they, and how do they actually learn?" },
            { type: "heading" as const, text: "The Basics: Layers and Neurons" },
            { type: "paragraph" as const, text: "A neural network is a computational model loosely inspired by the human brain. At its core, it consists of layers of interconnected nodes (neurons). The input layer receives raw data — pixels, tokens, or numerical features. The output layer produces a prediction. Between them, hidden layers learn increasingly abstract representations." },
            { type: "heading" as const, text: "Backpropagation: How Networks Learn" },
            { type: "paragraph" as const, text: "Learning happens through backpropagation combined with gradient descent. When the network makes a prediction, we compare it to the ground truth using a loss function. The error is propagated backwards, and each weight is nudged to reduce it. Repeat this millions of times over diverse data, and the network learns." },
            { type: "heading" as const, text: "What I've Learned Building Them" },
            { type: "paragraph" as const, text: "Working with neural networks practically — fine-tuning LLMs with LangChain, building classifiers with PyTorch — taught me that the math is only half the story. Architecture decisions, data quality, and training stability matter just as much. There is no substitute for running experiments yourself." },
        ],
    },
    {
        slug: "open-source-journey",
        title: "My Journey into Open Source",
        excerpt: "How contributing to open source changed my career trajectory.",
        date: "2023-11-20",
        readingTime: "5 min read",
        content: [
            { type: "paragraph" as const, text: "Open source is where I learned that software is fundamentally a social endeavour. My first contribution was a small bug fix — a one-line change to a library I used daily. The pull request was merged three days later. I was hooked." },
            { type: "heading" as const, text: "Starting Small" },
            { type: "paragraph" as const, text: "New contributors often wait until they're ready — until they know the codebase well enough, until their code is perfect. I didn't wait. I started with documentation fixes, test coverage, and small issues tagged 'good first issue'. Each contribution built context for the next." },
            { type: "heading" as const, text: "What It Taught Me" },
            { type: "paragraph" as const, text: "Reading other people's code is a superpower. Seeing how experienced engineers structure projects, write tests, and communicate in reviews fast-tracked my growth more than any tutorial could. Open source gave me access to mentorship at scale." },
            { type: "heading" as const, text: "The Compounding Effect" },
            { type: "paragraph" as const, text: "Over time, contributions compound. Maintainers remember you, reviewers trust your judgement, and your name appears in changelogs that thousands of people use. More importantly, you start to see yourself as someone who builds things that matter." },
        ],
    },
    {
        slug: "django-apis",
        title: "Building Scalable APIs with Django",
        excerpt: "Best practices for designing and implementing RESTful APIs.",
        date: "2023-09-10",
        readingTime: "7 min read",
        content: [
            { type: "paragraph" as const, text: "Django REST Framework (DRF) is one of the most mature API frameworks in any language. It handles serialization, authentication, permissions, and pagination — the plumbing you don't want to write from scratch." },
            { type: "heading" as const, text: "Design First" },
            { type: "paragraph" as const, text: "Before writing any code, write your API contract. What endpoints exist? What do requests and responses look like? This forces clarity upfront and prevents endless refactoring. Tools like OpenAPI/Swagger make this easy and produce documentation as a byproduct." },
            { type: "heading" as const, text: "Serializers Are Your Interface" },
            { type: "paragraph" as const, text: "DRF serializers do more than convert querysets to JSON. They validate input, handle relationships, and control what data is exposed. Treat them as your API's public interface — keep them thin, test them thoroughly, and resist adding business logic inside them." },
            { type: "heading" as const, text: "Scaling Considerations" },
            { type: "paragraph" as const, text: "When traffic grows, your database becomes the bottleneck first. select_related and prefetch_related are your first line of defence against N+1 query problems. Beyond that, caching with Redis and using async views for I/O-heavy operations will take you a long way." },
        ],
    },
    {
        slug: "type-systems",
        title: "The Power of Type Systems",
        excerpt: "Why TypeScript changed the way I think about code, and why you should care.",
        date: "2024-03-08",
        readingTime: "5 min read",
        content: [
            { type: "paragraph" as const, text: "I resisted TypeScript for longer than I should have. It felt like bureaucracy — writing types for things I already knew. The moment I stopped seeing types as overhead and started seeing them as documentation that can't go out of sync, everything clicked." },
            { type: "heading" as const, text: "Types as Communication" },
            { type: "paragraph" as const, text: "When you write a function signature in TypeScript, you're not just telling the compiler what to expect — you're telling the next developer (often future you) what this function does. The type system encodes your intent in a way that comments never can, because types are verified." },
            { type: "heading" as const, text: "Catching Errors Before Runtime" },
            { type: "paragraph" as const, text: "The ROI on TypeScript shows up most clearly in large codebases and refactors. When I rename a field or change a function signature, TypeScript finds every callsite that needs updating. No more hunting through logs for runtime errors that should have been caught statically." },
            { type: "heading" as const, text: "The Right Level of Strictness" },
            { type: "paragraph" as const, text: "Start with strict mode from the beginning. It's harder to retrofit later. Use unknown instead of any — it forces you to narrow the type before using it. Use discriminated unions instead of boolean flags. These habits compound over time into codebases that are genuinely easier to reason about." },
        ],
    },
    {
        slug: "finance-for-developers",
        title: "Finance for Developers",
        excerpt: "What I learned reading 50+ books on finance, distilled for technical minds.",
        date: "2024-02-14",
        readingTime: "6 min read",
        content: [
            { type: "paragraph" as const, text: "Developers are among the highest-paid professionals in the world, yet financial literacy rarely features in our education. After reading over 50 books on finance, investing, and economics, here are the ideas that stuck." },
            { type: "heading" as const, text: "Compounding Is the Only Magic" },
            { type: "paragraph" as const, text: "Albert Einstein allegedly called compound interest the eighth wonder of the world. Whether he said it or not, the math is irrefutable. Small, consistent contributions to appreciating assets over long time horizons produce outcomes that feel almost impossible — until you run the numbers." },
            { type: "heading" as const, text: "Index Funds Beat Almost Everyone" },
            { type: "paragraph" as const, text: "The evidence is overwhelming: most actively managed funds underperform their benchmark index over a 10-year horizon, after fees. For most people, low-cost index funds are not just adequate — they're optimal. The hard part is doing nothing when markets fall." },
            { type: "heading" as const, text: "Your Income Is Your Biggest Asset" },
            { type: "paragraph" as const, text: "Early in your career, optimising your earning power has a higher return than optimising your investment strategy. A 20% salary increase invested wisely will outperform even the best portfolio on a small principal. Invest in skills, networks, and opportunities first." },
        ],
    },
    {
        slug: "first-hackathon",
        title: "Lessons from My First Hackathon",
        excerpt: "What 48 sleepless hours building something together taught me about teams and shipping.",
        date: "2023-07-22",
        readingTime: "4 min read",
        content: [
            { type: "paragraph" as const, text: "I signed up for my first hackathon knowing almost nothing about what to expect. I came out knowing something about myself I hadn't known before: I work best under pressure, with a deadline that cannot move." },
            { type: "heading" as const, text: "Scope Ruthlessly" },
            { type: "paragraph" as const, text: "The most common hackathon failure mode is over-engineering. Teams spend 30 hours building infrastructure and 2 hours on the product. The winning teams I've observed do the opposite — they identify the single feature that demonstrates the idea and build only that, with enough polish to feel real." },
            { type: "heading" as const, text: "The Demo Is the Product" },
            { type: "paragraph" as const, text: "In a hackathon, you're not shipping software — you're shipping a narrative. The story of why this matters, who it's for, and why you're the team to build it matters more than your stack choice. A compelling demo with a broken backend beats a robust system with a boring pitch every time." },
            { type: "heading" as const, text: "What I'd Do Differently" },
            { type: "paragraph" as const, text: "Sleep. Even 4 hours changes the quality of your decisions in the final stretch. And commit to a stack you know — hackathons are the worst time to learn a new framework. Execution under constraints requires fluency, not curiosity." },
        ],
    },
    {
        slug: "code-review",
        title: "The Art of Code Review",
        excerpt: "How to give feedback that actually improves code — and the team.",
        date: "2023-05-04",
        readingTime: "5 min read",
        content: [
            { type: "paragraph" as const, text: "Code review is the highest-leverage activity in software development. A single well-placed comment can prevent hours of debugging, propagate a pattern across a codebase, or shape how a junior engineer thinks for years. Most teams treat it as a gate. The best teams treat it as a conversation." },
            { type: "heading" as const, text: "Distinguish Blocking from Non-Blocking" },
            { type: "paragraph" as const, text: "Not all feedback is equal. A security vulnerability blocks the PR. A naming preference is a suggestion. Make the distinction explicit — prefix comments with [blocking], [suggestion], or [nit]. This removes ambiguity and lets the author prioritise. Vague feedback creates friction; clear feedback creates trust." },
            { type: "heading" as const, text: "Ask Questions, Don't Make Demands" },
            { type: "paragraph" as const, text: "The best review comments are questions: 'What happens when this list is empty?' rather than 'Add a null check.' Questions preserve the author's agency, create a learning moment, and often reveal that you were missing context. You might be wrong — questions acknowledge that." },
            { type: "heading" as const, text: "Review the Design, Not the Style" },
            { type: "paragraph" as const, text: "Linters and formatters exist precisely so humans don't have to argue about spaces and semicolons. Use them. Reserve your review energy for correctness, architecture, edge cases, and maintainability. If you're spending more than 10% of review time on style, your tooling is doing too little." },
        ],
    },
    {
        slug: "building-in-public",
        title: "Building in Public",
        excerpt: "Why transparency about what you're creating is a competitive advantage, not a risk.",
        date: "2023-03-18",
        readingTime: "4 min read",
        content: [
            { type: "paragraph" as const, text: "The conventional wisdom is that you should keep your ideas secret until launch. The fear: someone will steal your idea. The reality: ideas are cheap, execution is rare, and the people most likely to see your work are potential users and collaborators, not competitors." },
            { type: "heading" as const, text: "Feedback Before You Finish" },
            { type: "paragraph" as const, text: "Sharing work in progress forces you to articulate what you're building and why, before you're too close to see it clearly. Early feedback is cheaper to act on than post-launch feedback. The friction of explaining your work to an outside audience is the same friction your users will face." },
            { type: "heading" as const, text: "Building an Audience as a By-product" },
            { type: "paragraph" as const, text: "People follow journeys, not products. A launch is a moment — a build is a story. When you document the process, the struggles, and the decisions, you create content that compounds. By the time you ship, there are people already rooting for you." },
            { type: "heading" as const, text: "What to Share and What to Keep" },
            { type: "paragraph" as const, text: "Share the process, the problems, and the progress. Keep proprietary business logic and sensitive data private. The goal is authenticity, not oversharing. A weekly update — what you built, what broke, what you learned — is enough to build a genuine following." },
        ],
    },
];
